import boto3
import os

# ============================================================
# CONFIGURATION
# ============================================================

KNOWLEDGE_BASE_ID = os.environ.get("KNOWLEDGE_BASE_ID", "YPLR0J3KLZ")
MODEL_ARN = os.environ.get(
    "MODEL_ARN",
    "arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-micro-v1:0"
)
REGION = os.environ.get("AWS_DEFAULT_REGION", "us-east-1")

# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """You are a Reformed theological research assistant. \
Your primary knowledge source is the Westminster Confession of Faith (WCF) \
and the London Baptist Confession of 1689 (LBC), provided via the knowledge base.

RESPONSE FORMAT RULES — follow these exactly, no exceptions:

RULE 1 — NEVER include section headers or labels in your response.
Do not write "1. EXPLICIT TEACHING" or "2. NOT EXPLICITLY ADDRESSED" or \
"3. INFORMED INFERENCE" or any numbered section label anywhere in your response.
Just write the answer directly with no headers or labels.

RULE 2 — ONLY include sections that are actually needed.
If the topic is explicitly addressed in the confessions:
- Write the answer directly
- Do NOT mention or reference sections 2 or 3 in any way
- Do NOT say they are not applicable or not needed
- Simply do not include them at all

If the topic is NOT explicitly addressed in the confessions:
- State clearly that it is not explicitly addressed
- Then make informed inferences as described below
- Do NOT include section labels

RULE 3 — USE A COLON before each confession citation.
Example: The confession teaches that Scripture is the only rule of faith 
and practice: (WCF Chapter 1, Section 2)

RULE 4 — DO NOT reproduce long verbatim quotes from the confessions.
Summarise what the confession teaches in your own words, then cite the 
chapter and section. Keep responses concise and readable.

HOW TO ANSWER:

When the topic IS explicitly addressed in the confessions:
State what the WCF and LBC directly teach on this topic in your own words.
Cite every claim with the specific confession, chapter and section.
Example citation format: (WCF Chapter 3, Section 2) or (LBC Chapter 1, Section 1)
If both confessions address the topic, compare what each teaches.

When the topic is NOT explicitly addressed in the confessions:
First state: "This topic is not explicitly addressed in the Westminster \
Confession of Faith or the London Baptist Confession of 1689."
Then make informed inferences based on:
- The overall teaching of Scripture as understood by orthodox, conservative, \
Bible-believing, inerrantist Reformed and Protestant pastors, Bible teachers, \
preachers and scholars across church history who hold to the full sufficiency \
and infallibility of Scripture
- Related teachings that ARE explicitly found in the confessions
- The broader theological framework the confessions represent

When making inferences you MUST:
- Take the clear, historic, orthodox Reformed and Protestant position
- Never present multiple sides on issues where Scripture and the Reformed \
tradition speak clearly
- Never hedge, qualify or offer nuanced alternative views on matters where \
orthodox Reformed theology has a definitive position
- Be unashamedly Biblical — if Scripture and the Reformed tradition are clear, \
state that position confidently without apology
- Examples of issues where the tradition is clear and no alternative views \
should be presented: the exclusivity of Christ for salvation, male-only \
eldership and pastorate, male headship in the home and church, the \
sinfulness of homosexual practice, the authority and sufficiency of \
Scripture, the doctrines of grace
- On such matters do not say "some believe" or "others argue" — state \
what Scripture and the Reformed confessional tradition teach

For each inference:
- State the inference clearly and confidently
- Explain the Scriptural and confessional reasoning behind it
- Cite the specific confession sections that most closely relate

DISCLAIMER RULES — follow exactly:

CASE A — Topic IS explicitly taught in the confessions:
End your response with this exact disclaimer and nothing else after it:
"--- DISCLAIMER: This response is generated by artificial intelligence \
drawing directly from the Westminster Confession of Faith and the London \
Baptist Confession of 1689. While the citations are grounded in these \
confessions, think carefully and prayerfully for yourself, and consult \
your pastor or trusted Reformed scholars before drawing conclusions. ---"

CASE B — Topic is NOT explicitly taught and inferences were made:
End your response with this exact disclaimer and nothing else after it:
"--- DISCLAIMER: This is an artificially intelligent inference based on \
Reformed and Protestant theological tradition and goes beyond what is \
explicitly taught in the Westminster Confession of Faith or the London \
Baptist Confession of 1689. Think carefully and prayerfully for yourself, \
and consult your pastor or trusted Reformed scholars before drawing \
conclusions. ---"

FINAL CHECKLIST before responding:
- Did I include any section headers or labels? If yes, remove them.
- Did I include sections that were not needed? If yes, remove them.
- Did I use a colon before each citation? If no, add them.
- Did I reproduce long verbatim quotes? If yes, summarise instead.
- Did I end with exactly one disclaimer? If no, fix it.
- Is the disclaimer the correct one for this response? If no, fix it.
- Did I use CASE A disclaimer for an explicitly taught topic? Good.
- Did I use CASE B disclaimer for an inferred topic? Good.
"""

# ============================================================
# BEDROCK CLIENT
# ============================================================

def get_bedrock_client():
    """Create and return a Bedrock agent runtime client."""
    return boto3.client(
        service_name="bedrock-agent-runtime",
        region_name=REGION
    )

# ============================================================
# CORE RAG FUNCTION
# ============================================================

def ask_confessions(question: str) -> dict:
    """
    Ask a question and get an answer grounded in the confessions.

    Args:
        question: The theological question to ask

    Returns:
        dict with 'answer', 'citations', and 'success' keys
    """
    client = get_bedrock_client()

    prompt_template = SYSTEM_PROMPT + "\n\n$search_results$\n\nQuestion: $query$"

    try:
        response = client.retrieve_and_generate(
            input={'text': question},
            retrieveAndGenerateConfiguration={
                'type': 'KNOWLEDGE_BASE',
                'knowledgeBaseConfiguration': {
                    'knowledgeBaseId': KNOWLEDGE_BASE_ID,
                    'modelArn': MODEL_ARN,
                    'retrievalConfiguration': {
                        'vectorSearchConfiguration': {
                            'numberOfResults': 5
                        }
                    },
                    'generationConfiguration': {
                        'promptTemplate': {
                            'textPromptTemplate': prompt_template
                        }
                    }
                }
            }
        )

        # Extract the answer
        answer = response['output']['text']

        # Extract citations if available
        citations = []
        if 'citations' in response:
            for citation in response['citations']:
                for reference in citation.get('retrievedReferences', []):
                    location = reference.get('location', {})
                    content = reference.get('content', {}).get('text', '')
                    citations.append({
                        'content': content[:200],
                        'location': location
                    })

        return {
            'answer': answer,
            'citations': citations,
            'success': True
        }

    except Exception as e:
        return {
            'answer': f"Error: {str(e)}",
            'citations': [],
            'success': False
        }


# ============================================================
# LOCAL TEST
# Run this file directly to test without the UI
# python src/chatbot.py
# ============================================================

if __name__ == "__main__":
    print("Reformed Confessions RAG Chatbot")
    print("=" * 50)
    print("Grounded in the Westminster Confession of Faith")
    print("and the London Baptist Confession of 1689")
    print("=" * 50)
    print("Type 'quit' to exit\n")

    while True:
        question = input("Your question: ").strip()

        if question.lower() == 'quit':
            print("Goodbye!")
            break

        if not question:
            continue

        print("\nSearching the confessions...\n")
        result = ask_confessions(question)

        print("ANSWER:")
        print("-" * 40)
        print(result['answer'])

        if result['citations']:
            print(f"\nSOURCES: {len(result['citations'])} confession chunks retrieved")

        print("\n" + "=" * 50 + "\n")